name: IPFS Update Times

on: 
  workflow_dispatch:
  schedule:
    - cron: '23 * * * *'

jobs:
  IPFS-Update-Times:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install sqlite3 (only needed for nektos/act medium sized docker)
        run: |
          sudo apt update;
          sudo apt install sqlite3;
      - name: Download latest ipfs-update
        run: |
          LATEST=$(curl https://dist.ipfs.io/ipfs-update/versions | tail -n1);
          curl "https://dist.ipfs.io/ipfs-update/${LATEST}/ipfs-update_${LATEST}_linux-amd64.tar.gz" > latest.tar.gz;
          tar xvfz latest.tar.gz;
      - name: Timed Run of ipfs-update Fetching the Latest Version
        continue-on-error: true
        run: |
          START=$SECONDS
          ./ipfs-update/ipfs-update fetch latest >output
          DURATION=$(($SECONDS-$START))
          sqlite3 ./ipfs-update-times/timeseries.db <<EOF
          CREATE TABLE IF NOT EXISTS log ( ID INTEGER PRIMARY KEY, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP, output TEXT,  duration INTEGER);
          INSERT INTO log ( output, duration )
          VALUES ( readfile("output"), "$DURATION");
          EOF
      - name: Commit to Posterity
        uses: EndBug/add-and-commit@v9
        with:
          add: ipfs-update-times/timeseries.db
          author_name: Danny
          author_email: danny@spesh.com
          message: "[automated] Update IPFS-Update-Times."
